[alias]
dgbundle = "run --package dagrid-xtask --release -- bundle dagrid-plugin-export"
dgflamegraph = "flamegraph -p dagrid-benchmarks"
dgbench = "bench -p dagrid-benchmarks"
dgtest = "test -p dagrid-core"
dgplug = "build -p dagrid-plugin-export"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
